backend:
  build: backend
  environment:
    - DATABASE_URL=postgres://votingapp:votingapp@db/votingapp
  links:
   - db
  ports:
   - "8080:8080"

frontend:
  build: frontend
  ports:
   - "3000:3000"

db:
  image: postgres:9.4
  environment:
    - POSTGRES_USER=votingapp
    - POSTGRES_PASSWORD=votingapp
    - POSTGRES_DB=votingapp
  volumes:
    - db_data:/var/lib/postgresql/data
