backend:
  build: backend
  environment:
    - DATABASE_URL=postgres://votingapp:votingapp@db/votingapp
  links:
   - db
  ports:
   - "8080:8080"
  volumes:
    - ./backend:/usr/src/app

frontend:
  build: frontend
  ports:
   - "3000:3000"
  volumes:
    - ./frontend:/usr/src/app

db:
  image: postgres:9.4
  environment:
    - POSTGRES_USER=votingapp
    - POSTGRES_PASSWORD=votingapp
    - POSTGRES_DB=votingapp
