---
- name: Install curl
  apt: pkg={{ item }} state=latest
  with_items:
    - curl

- name: Add nodejs source to package manager
  shell: curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -

- name: Install nodejs
  apt: pkg={{ item }} state=latest
  with_items:
    - nodejs
